### ISSUE TITLE
How to add FW to the archive?

### ISSUE THREAD

**Issue by bacon-avenger** [AT0myks/reolink-fw-archive#2]
I have an older one for the RLC-510WA that is currently not downloaded via the script, v3.1.0.0.956_22041512.  Is this of interest to add?

**Comment by AT0myks** [comment]
Any missing firmware is welcome to be added. If you have the original link you can just share it here and I'll add it. But I assume you only have the actual file, so in that case you could try to attach it to your message, or if it's too big upload it to a file sharing website.

**Comment by bacon-avenger** [comment]
That would be correct, I just have the file, and yes, it's too big to attach here (29 MB)

This link should be accessible:
https://drive.google.com/file/d/1ENIQ_7cGWGygM1wSZjiIHuRPD_IrIuCz/view

**Comment by AT0myks** [comment]
Thank you for adding a missing firmware.

**Comment by jurasjo** [comment]
I have this camera with the FW version [v3.1.0.764_21121712]. 
Looks like the firmware provided here is not the proper one. When I hit the upgrade button it shows: `"New firmware update is available."` and starts upgrading process but after few second it stops: `"Upgrade Failed. Failed to recognize the file format. Please try again.".`

**Comment by AT0myks** [comment]
What's the name of the file?
Try updating again after renaming it to `IPC_523128M5MP.956_22041512.RLC-510WA.OV05A10.5MP.WIFI1021.REOLINK.pak`

**Comment by jurasjo** [comment]
The name of the file from provided link is:
```RLC-510WA__IPC_523128M5MP__v3.1.0.0.956_22041512.pak```
After changing to what you have advised it can be properly flashed.
```IPC_523128M5MP.956_22041512.RLC-510WA.OV05A10.5MP.WIFI1021.REOLINK.pak```
Thank you.

PS
Maybe it would be good to add a note about this in the table (NOTES) on the main page.

**Comment by AT0myks** [comment]
Thanks for the feedback. This is the unfortunate result of Reolink's weird update file check.
A note has been added for future readers.
