### ISSUE TITLE
RLC-510A V2 Firmware with important changes missing - link provided

### ISSUE THREAD

**Issue by user45876** [AT0myks/reolink-fw-archive#23]
Reolink does not offer the Firmware with the frame rate change on their download center. Thanks to a good soul on reddit, there is a link to the RLC-510A V2 FW:

Reddit Post with Link: https://www.reddit.com/r/reolinkcam/comments/y5awnz/firmware_for_rlc510a_v2/
Direct link to FW on Reolink Server: https://support.reolink.com/attachments/token/UmdVaKU7erG8omgOIiciOZWcr/?name=IPC_523128M5MP_V2.1228_22082200.RLC-510A.OV05A10.5MP.REOLINK.pak

Also find the file attached - hab to split it to stay below 25MB per piece.

[IPC_523128M5MP_V2.1228_22082200.RLC-510A.OV05A10.5MP.REOLINK.zip.001.zip](https://github.com/AT0myks/reolink-fw-archive/files/11914601/IPC_523128M5MP_V2.1228_22082200.RLC-510A.OV05A10.5MP.REOLINK.zip.001.zip)
[IPC_523128M5MP_V2.1228_22082200.RLC-510A.OV05A10.5MP.REOLINK.zip.002.zip](https://github.com/AT0myks/reolink-fw-archive/files/11914602/IPC_523128M5MP_V2.1228_22082200.RLC-510A.OV05A10.5MP.REOLINK.zip.002.zip)

**Comment by jurasjo** [comment]
I think this version is already listed in this repo.

**Comment by user45876** [comment]
You are absolutely right and I seem to be blind. There's even an newer one ;) Sorry and thank you.
