### ISSUE TITLE
Download location "https://home-cdn.reolink.us/" trustful?

### ISSUE THREAD

**Issue by Sandworm-of-Dune** [AT0myks/reolink-fw-archive#38]
Hi,
I recognized that most of the firmware pakages are located or linked to domain 
https://home-cdn.reolink.us/

e.g for 523WA: 
https://home-cdn.reolink.us/wp-content/uploads/2023/11/140140231699926023.7448.zip?download_name=523WA_v3102831_23102508_v10031.zip

This isn't the official Reolink doamin.
If I go the the site directly I get the following message:
![grafik](https://github.com/AT0myks/reolink-fw-archive/assets/91150538/0e09fa41-08b7-40fd-b30c-6d83237c8fcc)
Whom belong this webside. Is the download trustful?
Thanks for clarification.
Regards

**Comment by AT0myks** [comment]
This is an official Reolink domain, but as the name implies it's a [CDN](https://en.wikipedia.org/wiki/Content_delivery_network). It's not meant to be the "official" site, it's used to serve content. In case you end up on this page they show this message to redirect you to reolink.com. If you look at the network requests when you to reolink.com you'll see that some files are served by this domain. The link you show is the same one that's on their download center right now. So yes it's safe to download.

**Comment by Sandworm-of-Dune** [comment]
Thanks for clarification.
Regards
