### ISSUE TITLE
Readme stop working

### ISSUE THREAD

**Issue by milandzuris** [AT0myks/reolink-fw-archive#48]
![image](https://github.com/AT0myks/reolink-fw-archive/assets/42905545/7c3fe344-cc07-4353-9b41-0afeed1301c3)

**Comment by gkchim** [comment]
How do i use this repository please?

**Comment by milandzuris** [comment]
@AT0myks

**Comment by zeus86** [comment]
seem liste the github bot breaks the readme continuously. see the version history of readme.md, and search for the newest version not changed by the github-bot, and view these instead (click on the readme-file, in the upper right bar select "history", and then choose your version with the icon "View code atthis point"). as of right now it is this one from 2023-12-23:   
https://github.com/AT0myks/reolink-fw-archive/blob/8b276e1dbea361db8051f07560c824d0c5a10028/README.md

**Comment by AT0myks** [comment]
Thanks for the report, and thanks to @zeus86 for providing steps to work around the issue. This was mentioned in #45 and is now fixed.
